### ISSUE TITLE
DeepSparse and OpenVINO are not working with python 3.10

### ISSUE THREAD

**Issue by valeriosofi** [nebuly-ai/nebullvm#103]
Currently DeepSparse and OpenVINO are not activated with python 3.10, we must wait until they are full supported.

**Comment by jiwaszki** [comment]
Hi @valeriosofi , I am happy to tell you that OpenVINO is going to extend support to Python 3.10!
It is already on current main branch if you want to try it out, take a look at https://github.com/openvinotoolkit/openvino/pull/12578 and https://github.com/openvinotoolkit/openvino/pull/13243

Let me (or my collegue @p-wysocki) know if you need any help with OpenVINO, cheers!

**Comment by valeriosofi** [comment]
Thanks @jiwaszki, we are looking forward to try it with python 3.10!

**Comment by diegofiori** [comment]
solved in #127
