### ISSUE TITLE
Bug on colab while installing on colab

### ISSUE THREAD

**Issue by bhattbhuwan13** [nebuly-ai/nebullvm#112]
The following piece of code shows error while running on colab(nebullvm not found). However, despite the error, the optimization process is still successful.
```
python -m nebullvm.installers.auto_installer \
    --frameworks torch onnx tensorflow huggingface \
    --compilers all
```

**Comment by valeriosofi** [comment]
Hello @bhattbhuwan13, could you please share with us your Colab notebook so that we can check the issue?
