### ISSUE TITLE
Documentations for open_alpha_tensor

### ISSUE THREAD

**Issue by BrianPulfer** [nebuly-ai/nebullvm#138]
Currently, all methods and classes under `apps/accelerate/open_alpha_tensor` are missing documentation/descriptions. Such documentation is especially useful for both end users and new contributors to get a sense of the role of each component in the package and all options in the various methods.

I volunteer to add documentation to the methods and classes of this package.

**Comment by diegofiori** [comment]
Thank you @BrianFulfer, much appreciated! Please go ahead and open pull requests with docs for OpenAlphaTensor’s methods and classes!
