### ISSUE TITLE
Automatically syncing GitBook documentation with repo's README files

### ISSUE THREAD

**Issue by BrianPulfer** [nebuly-ai/nebullvm#139]
Currently, there is a mismatch between the repo's README files and the online documentation obtained with GitBook.

As an example, [the README documentation](https://github.com/nebuly-ai/nebullvm/tree/main/apps/accelerate/speedster) to get started with `speester` differs from the one on the [website](https://docs.nebuly.com/speedster/installation).

README
<img width="1049" alt="Screenshot 2023-01-06 at 00 29 13" src="https://user-images.githubusercontent.com/42559439/210899579-817207f4-c713-44aa-821d-cbfcc6177ac7.png">

Website
<img width="805" alt="Screenshot 2023-01-06 at 00 29 48" src="https://user-images.githubusercontent.com/42559439/210899642-bfeeda6e-df5d-4e4d-b0d6-514b17837f60.png">

In fact, the website command to get started with speedster does not work properly right now.

It may be beneficial to automatically update the online website as soon as the README files are updated in the main branch.

**Comment by diegofiori** [comment]
Hello @BrianPulfer! We changed the auto-installer interface in 95d588aa8a81f43057a6b5be7dce354e85540394 but we haven't released it on PyPi yet. We are going to change the documentation with the next release.
