### ISSUE TITLE
Bug in TVM installation (on CPU) for Ubuntu 18.04 systems

### ISSUE THREAD

**Issue by morgoth95** [nebuly-ai/nebullvm#15]
The auto-installer fails to install TVM correctly due to llvm not being installed on Ubuntu 18.04 systems. In fact, the command 
```
sudo apt-get install llvm12
```
fails in Ubuntu 18.04 since llvm12 seems to be not supported. I tested the OS with llvm10 and it seems to work.
So, to solve this issue it should be enough to locate the version of ubuntu and for 18.04 install lllvm10 instead of llvm12.
I installed llvm10 with the following command
```
sudo apt-get install llvm-10 lldb-10 llvm-10-dev libllvm10 llvm-10-runtime
```

**Comment by smeetdc** [comment]
Hi, I was able to build and install LLVM-12 on Ubuntu 18.04 and then build TVM.  No incompatibility issues between those specific versions of LLVM and OS.
