### ISSUE TITLE
Has Meta released the sourcecode for LLaMa? How was ChatLLaMa trained?

### ISSUE THREAD

**Issue by NightMachinery** [nebuly-ai/nebullvm#186]
Has Meta released the sourcecode for LLaMa? How was ChatLLaMa trained?

**Comment by Riroaki** [comment]
https://github.com/facebookresearch/llama

**Comment by diegofiori** [comment]
Hi @NightMachinery, thanks for reaching out. This library implements the training process to create your own personalized chatllama assistant. You should fill in [Meta's form](https://forms.gle/jk851eBVbX1m5TAv5) to access the weights.
