### ISSUE TITLE
Haven't you given me the application form email? Do not know who has applied successfully, can pay to purchase the training set

### ISSUE THREAD

**Issue by haxx12113** [nebuly-ai/nebullvm#193]
Haven't you given me the application form email? Do not know who has applied successfully, can pay to purchase the training set

**Comment by PierpaoloSorbellini** [comment]
Hi @haxx12113, thank you for your interest in the project. LLaMA weights are only available if requested directly from MetaAI. Our project is open source and does not require any payment.
