### ISSUE TITLE
Have the llama weights been uploaded to bittorrent yet, to make them publicly accessible?

### ISSUE THREAD

**Issue by distbit0** [nebuly-ai/nebullvm#194]
If not, is anyone working on this/planning to upload them?

**Comment by 3awny** [comment]
would be really nice :D

**Comment by diegofiori** [comment]
Hi @distbit0, uploading the weights on bittorrent would be against the License distributed by Meta for LLaMA's weights. Up-to-date the LLaMA weights can be obtained only using Meta official [google form](https://forms.gle/jk851eBVbX1m5TAv5).
