### ISSUE TITLE
No module named `loguru`

### ISSUE THREAD

**Issue by cyclotomicextension** [nebuly-ai/nebullvm#198]
I have been trying to build up on the nebullvm implemetation of forward-forward and use some of the built in libraries. However, I am unable to run it on VSCode or codespaces or colab. I am getting the following error:
```
from loguru import logger
ModuleNotFoundError: No module named 'loguru'
```

**Comment by valeriosofi** [comment]
Hello @cyclotomicextension, you can solve that by running `pip install loguru`😉

**Comment by cyclotomicextension** [comment]
Oh right, thanks! Seems like I have lost some braincells 😅
