### ISSUE TITLE
[Chatllama] Question: How to load the ChatLLaMA model weights from the directory for training? Also, can you provide a sample of the training data?

### ISSUE THREAD

**Issue by Alla-Abdella** [nebuly-ai/nebullvm#200]

**Comment by diegofiori** [comment]
Hi @Alla-Abdella, thank you for contacting us! We are currently working on refining our code and we will release some training data examples very soon.

**Comment by muzamil47** [comment]
Hi @diegofiori,

I am also looking for the sample dataset to prepare custom dataset for training the ChatLLaMA model.

**Comment by PierpaoloSorbellini** [comment]
Hi @muzamil47 you can find what you have asked for in artifacts/dataset. 
Feel free to open a new issue if something is not clear.
