### ISSUE TITLE
ImportError: cannot import name 'cfgs_to_fx_cfgs' from 'nebullvm.optional_modules.neural_compressor'

### ISSUE THREAD

**Issue by valeriosofi** [nebuly-ai/nebullvm#205]
When installing and using the latest release of speedster in colab, it throws the following error: `ImportError: cannot import name 'cfgs_to_fx_cfgs' from 'nebullvm.optional_modules.neural_compressor' (/usr/local/lib/python3.8/dist-packages/nebullvm/optional_modules/neural_compressor.py)`

**Comment by valeriosofi** [comment]
It can be solved by updating the numpy version: `pip install "numpy>=1.22.0,<1.24.0"`

**Comment by mapo80** [comment]
Hi, I've the same problem.
I've tried to execute this:
> pip install "numpy>=1.22.0,<1.24.0"

Bu I have this message
> Requirement already satisfied: numpy<1.24.0,>=1.22.0

I have 1.23.1 version

**Comment by valeriosofi** [comment]
Hello @mapo80, are you using Google colab as well? If so, have you tried rebooting the notebook kernel?
