### ISSUE TITLE
ModuleNotFoundError: No module named 'config'

### ISSUE THREAD

**Issue by MohamedAliRashad** [nebuly-ai/nebullvm#207]
`chatllama` is not able to import config

**Comment by ming1523** [comment]
adding chatllama.rlhf. in the front seems solve this issus

**Comment by diegofiori** [comment]
Hi @MohamedAliRashad and @ming1523, thanks for pointing out the error. We are currently fixing multiple bugs, you can see the updates on #203.

**Comment by ming1523** [comment]
> Hi @MohamedAliRashad and @ming1523, thanks for pointing out the error. We are currently fixing multiple bugs, you can see the updates on #203.
thanks, can you share the training dataset as an example? new to chatgpt like model, not sure how to organize data;

**Comment by my20000stars** [comment]
I installed config to solve this problem but then ImportError: cannot import name 'ConfigActor' from 'config' shown.

**Comment by MohamedAliRashad** [comment]
@my20000stars It needs its own config not the library called `config` (I think)
