### ISSUE TITLE
generate_dataset.py Error

### ISSUE THREAD

**Issue by seasidemym** [nebuly-ai/nebullvm#214]
python generate_dateset.py [https://github.com/nebuly-ai/nebullvm/tree/main/apps/accelerate/chatllama/generate_dataset.py]
ImportError: cannot import name 'ConversationalBufferWindowMemory' from 'langchain.chains.conversation.memory'

look into /root/miniconda3/lib/python3.7/site-packages/langchain/chains/conversation/memory.py, only ConversationBufferMemory /ConversationSummaryMemory func. 

which python version and langchain version should be chosen?

**Comment by seasidemym** [comment]
python 3.8.8
langchain 0.0.103

ConversationalBufferWindowMemory -> ConversationBufferWindowMemory works

**Comment by diegofiori** [comment]
Fixed in #212. It should work now pulling the latest commit.
