### ISSUE TITLE
path_to_config_file.yaml

### ISSUE THREAD

**Issue by DarylLei** [nebuly-ai/nebullvm#215]
hello，Where can I see a reference example

**Comment by PierpaoloSorbellini** [comment]
Hi @DarylLei, thank you so much for reaching out. Today, we are going to release a more stable version of ChatLLaMA, with more detailed documentation. Thank you for your feedback, let us know if after the release there is still something missing or unclear.

**Comment by diegofiori** [comment]
Closing the issue since examples have been provided in the new readme #204.
