### ISSUE TITLE
what is the training data format in chatllama actor_config/reward_config.

### ISSUE THREAD

**Issue by lonelydancer** [nebuly-ai/nebullvm#217]
can you release some data sample?

**Comment by diegofiori** [comment]
Hi @lonelydancer, thank you for reaching out. Today, we are gonna release a new readme with more extensive examples. Please let us know if you have any other feedback.

**Comment by Vincent131499** [comment]
Please explain the way of distributed training in detail.

**Comment by diegofiori** [comment]
Data examples for reward training has been released with #203. For updates on distributed training see #242 and #229
