### ISSUE TITLE
[Chatllama] cannot import name 'TrainingStats' from 'utils'

### ISSUE THREAD

**Issue by caldwbr** [nebuly-ai/nebullvm#232]
I got all the way, but at the last step, "python artifacts/main.py artifacts/config/config.yaml --type REWARD" it is throwing all kinds of errors, such as "cannot import name 'TrainingStats' from 'utils'," not liking the command "sudo," not wanting to download chocolatey on windows 11 while simultaneously saying I already both have and don't have chocolatey.... Arrg

**Comment by diegofiori** [comment]
Hi @caldwbr, thank you for contacting us. Could you please share your current hardware configuration with us so that we can replicate the error and provide a possible solution?

**Comment by PierpaoloSorbellini** [comment]
Hi @caldwbr make sure to install the correct repo with pip. 
The correct one is `pip install chatllama-py` while there is a copy that is not working from someone else that is
`pip install chatllama`. 
With the correct package you should not have this problem. 
Thank you :)
