### ISSUE TITLE
[Chatllama] Generate Data Error on tutorial 

### ISSUE THREAD

**Issue by yicheng-2019** [nebuly-ai/nebullvm#265]
I run the GetStart but the dataset has the error

(llama) qiuyc@qiuyc-3090:~/code/Chatllama/chatllama-nebullvm$ python artifacts/main.py artifacts/config/config.yaml --type ALL
Current device used :cuda
No previous model found at ./models/reward for model gpt2-large.pt
Loading dataset from ./datasets/reward_training_data.json
Loaded 200 samples
Start Training the Reward Model
Looking for checkpoints...
Found checkpoint for epoch 1, step 10...
Loading ...
Epoch: 1/32, Iteration: 11/25, Training Loss: 3.4106693267822266
prediction [4.451936  3.87707   5.655977  4.2465377 2.3933697 5.1995487 4.347823
 5.8636036] target [4.  3.  2.  3.  4.  4.5 4.  3. ]
Epoch: 1/32, Iteration: 12/25, Training Loss: 2.217592477798462
prediction [2.7735171 5.110946  5.260797  5.696887  4.2918286 2.9091988 5.3532596
 4.6064796] target [3. 3. 4. 4. 3. 4. 3. 4.]
Epoch: 1/32, Iteration: 13/25, Training Loss: 3.16831636428833
prediction [2.6523368 5.0899324 5.2925634 4.878763  4.6527834 5.071644  4.953468
 4.7791476] target [4. 2. 3. 4. 3. 4. 4. 3.]
Epoch: 1/32, Iteration: 14/25, Training Loss: 1.3716436624526978
prediction [4.5529017 4.795724  5.041059  4.568875  2.6253047 5.424052  4.8917665
 3.5276096] target [4.  4.5 4.  3.  3.  3.  4.  4. ]
Epoch: 1/32, Iteration: 15/25, Training Loss: 1.31028413772583
prediction [5.3360367 4.746885  3.1630383 4.666844  4.6595182 2.9819224 4.9737635
 4.466095 ] target [4. 4. 2. 3. 3. 4. 5. 4.]
Traceback (most recent call last):
  File "artifacts/main.py", line 57, in <module>
    reward_trainer.train()
  File "/home/qiuyc/code/Chatllama/chatllama-nebullvm/chatllama/rlhf/reward.py", line 404, in train
    for i, inputs in enumerate(self.train_dataloader):
  File "/home/qiuyc/anaconda3/envs/llama/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/qiuyc/anaconda3/envs/llama/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 692, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/qiuyc/anaconda3/envs/llama/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/qiuyc/anaconda3/envs/llama/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/qiuyc/code/Chatllama/chatllama-nebullvm/chatllama/rlhf/reward.py", line 239, in __getitem__
    score = float(self.data[idx]["score"])
TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by PierpaoloSorbellini** [comment]
Hi @yicheng-2019  
Yes this error is a result of the fact that it may happen that Davinci is unable to assign a score to a text and then when training the reward model the score is still None and training fails. 
We have added additional checks on the reward training dataset so that it shouldn't happen anymore. 
You can already try the fixed version from the PR #233 . 
Thanks for your input and let us know if the problem persist.

**Comment by yicheng-2019** [comment]
Ok, thanks for your help
