### ISSUE TITLE
[Chatllama] 3B to 13B → 4x Nvidia A100 (80Gb)?

### ISSUE THREAD

**Issue by CS123n** [nebuly-ai/nebullvm#270]
Hi, if the batch size is 1, do I still need 4 A100 to start the training process? What is the minimal memory requirements?

**Comment by PierpaoloSorbellini** [comment]
Hi @CS123n. 
Thanks for your interest in this project. 
The memory requirements depend heavily on the model and batch you are using. 
For models with billions of parameters at least an A100 is recommended with the current training setup.
We are looking to make training lighter by using adapters as a future development, but first we are trying to test the training pipeline to make it as robust as possible. 
More details on training minimum hardware requirements are going to be released as soon as we finish our testing with various models.
