### ISSUE TITLE
[ChatLlama] Train Actor with llama-7b model Error initializing torch.distributed using env:// rendezvous: 

### ISSUE THREAD

**Issue by balcklive** [nebuly-ai/nebullvm#292]
When I train actor model with llama-7b, I got this:

Current device used :cuda
local_rank: -1 world_size: -1
Traceback (most recent call last):
  File "artifacts/main.py", line 50, in <module>
    actor_trainer = ActorTrainer(config.actor)
  File "/home/zhoux/anaconda3/envs/py38/lib/python3.8/site-packages/chatllama/rlhf/actor.py", line 313, in __init__
    self.actor = ActorModel(config)
  File "/home/zhoux/anaconda3/envs/py38/lib/python3.8/site-packages/chatllama/rlhf/actor.py", line 57, in __init__
    local_rank, world_size = setup_model_parallel()
  File "/home/zhoux/anaconda3/envs/py38/lib/python3.8/site-packages/chatllama/llama_model.py", line 551, in setup_model_parallel
    torch.distributed.init_process_group("nccl")
  File "/home/zhoux/anaconda3/envs/py38/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 888, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/zhoux/anaconda3/envs/py38/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 235, in _env_rendezvous_handler
    rank = int(_get_env_or_raise("RANK"))
  File "/home/zhoux/anaconda3/envs/py38/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 220, in _get_env_or_raise
    raise _env_error(env_var)
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set

my config.yaml is as below:
trainer_config:
  # learning rates
  actor_lr: 0.00001
  critic_lr: 0.00001
  # PPO Hyperparameters
  actor_eps_clip: 0.2
  critic_eps_clip: 0.2
  beta_s: 0.02
  # path to examples to be sampled (training dataset) see rlhf_dataset.json
  examples_path: "./datasets/rlhf_training_data.json"
  # number of episodes and generation performed for each episode
  # in the train() method
  num_episodes: 5
  max_timesteps: 1
  # number of timesteps after which the learn() method is called 
  # (to update the weights)
  update_timesteps: 1
  # number of example sampled at each timestep
  num_examples: 8
  # batch and epochs for the training
  batch_size: 1
  epochs: 1
  # number of learning steps (i.e. learn()) after which a checkpoint is saved
  checkpoint_steps: 5
  checkpoint_name: null

actor_config:
  model: "llama-7B"
  model_folder: "/home/zhoux/models/actor_model"
  tokenizer_path: "/home/zhoux/models/actor_tokenizer"
  train_dataset_path: "./datasets/actor_training_data.json"
  validation_dataset_path: null
  # froze model embedding during training
  froze_embeddings: True
  # use fairscale layers to build the model instead of vanilla pytorch
  use_fairscale: False
  # max sequence length for the actor (i.e. prompt + completion) it depends on
  # the model used.
  max_sequence_length: 1500
  # max tokens generated by the actor (completion only)
  max_tokens: 2048
  # minimum number of tokens generated by the actor
  min_tokens: 100
  # additional prompt tokens to be used for template or as safety
  additonal_prompt_tokens: 20
  # temperature for the actor
  temperature: 0.5
  batch_size: 1
  # number iteration after print
  iteration_per_print: 1
  lr: 0.000009
  epochs: 2
  # number of backpropagation after saving the checkpoints
  checkpoint_steps: 10000000000
  # number of checkpoints to keep while removing the older 
  # (keep memory consumption of checkpoints reasonable)
  n_checkpoints_to_keep: 5
  # here specify the name of the actor checkpoint from which resume 
  # during actor training. If null load the last one.
  checkpoint_name: null
  # deepspeed settings
  deepspeed_enable: False
  deepspeed_config_path: "./artifacts/config/ds_config.json"
  # accelerate settings
  accelerate_enable: False

**Comment by PierpaoloSorbellini** [comment]
Hi @balcklive, Thanks for reaching out! 
When starting a distributed training, the instances need to have the RANK environment variable set. It seems to be missing in your setup! If you are using llama 7b, you will need at least more than one GPU, in which case it would be recommended to configure your setup and config.yaml for distributed training (DeepSpeed's, Accelerate). If you choose llama as your model, the method to initialise the process group will always be called, because it's expecting at least more than one GPU. We know that at the moment this type of training requires a bit of experience and involvement from whoever is using the repo, and would like to improve this experience to make things smoother. 

To remove the error when using a single GPU you can just comment the line 58 in actor.py

`
local_rank, world_size = setup_model_parallel()
`

We are currently working on having some flag in the config.yaml to manage this type of behaviour.

**Comment by balcklive** [comment]
OK, thank you for your reply, I will close this issue with your answer.
Now I changed a machine with 8 GPUs, when I train this:
torchrun --nproc_per_node 8 artifacts/main.py artifacts/config/config.yaml --type REWARD
It can normaly run, but only one GPU is used.
when I train this
torchrun --nproc_per_node 8 artifacts/main.py artifacts/config/config.yaml --type ACTOR
I still got the this error:
AssertionError: Loading a checkpoint for MP=0 but world size is 8
Traceback (most recent call last):
  File "artifacts/main.py", line 50, in <module>
    actor_trainer = ActorTrainer(config.actor)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/chatllama/rlhf/actor.py", line 314, in __init__
    self.actor = ActorModel(config)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/chatllama/rlhf/actor.py", line 61, in __init__
    self.model, self.tokenizer = load_model(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/chatllama/llama_model.py", line 625, in load_model
    checkpoint, params = load_checkpoints(ckpt_dir, local_rank, world_size)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/chatllama/llama_model.py", line 603, in load_checkpoints
    assert world_size == len(checkpoints), (


I also tried accelerator and deepspeed, it got the same result.
Is there any way that I can run with mutiGPUs easily?

**Comment by LinZhiLuZhiLin** [comment]
"I still got the this error:
AssertionError: Loading a checkpoint for MP=0 but world size is 8"

Me,too. Have you make it correct?
