### ISSUE TITLE
[ChatLLaMA] train RL on multi-gpu

### ISSUE THREAD

**Issue by EthanChen1234** [nebuly-ai/nebullvm#307]
Hi, thanks for your great job.

I'm training actor and reward, setting " deepspeed_enable: True" to enable multi-gpu training.

But, when training the RL with multi-gpu, I encountered various errors.

could you send me the  config.yaml and starting command for RL multi-gpu training?

**Comment by EikeKohl** [comment]
Hi @EthanChen1234,
I implemented a fix for my fork that worked for me. I will open a branch + PR today so you can try it out 🙂.

**Comment by PierpaoloSorbellini** [comment]
Hi @EthanChen1234 that is amazing, thanks very much! 
I am looking forward to seeing the PR.
<3

**Comment by EikeKohl** [comment]
Hello everyone, sorry for the delay. When working with my fork, I noticed some issue and tried to fix them + I did not find the time to create the public GitHub fork.

This is my PR: https://github.com/nebuly-ai/nebullvm/pull/316
Please note that the conversation log saving is yet to be fixed. But the multi GPU RL training worked for me:

![image](https://user-images.githubusercontent.com/57795397/229082284-e212782d-e861-4dcb-9097-4c785dcd3a29.png)

Feel free to give feedback on improvements or to report bugs 🙂
