### ISSUE TITLE
module not found:chatllama.rlhf.dataset

### ISSUE THREAD

**Issue by MuffinC** [nebuly-ai/nebullvm#324]
Hi! i've already ran the setup.py, requirements.txt and also installed chatllama-py. But when i run python artifacts/main.py artifacts/config/config.yaml --type ALL. It gives the error
ModuleNotFoundError: No module named 'chatllama.rlhf.dataset'
Please advise on what exactly am i missing! Also have all the datasets downloaded

**Comment by laozhanghahaha** [comment]
@MuffinC hey I also met this problem, have you solved it?
