### ISSUE TITLE
ModuleNotFoundError: No module named 'openvino'

### ISSUE THREAD

**Issue by messmor** [nebuly-ai/nebullvm#37]
When installing via "pip install nebullvm" the install goes through. However, when calling "python -c "import nebullvm" " to install the the different DL compilers, I am greeted by a ModuleNotFoundError for the module openvino. pip installing openvino only causes further errors. The read me says these errors/warnings can be ignored on this initial import, yet they persist for every other import, making the package unusable.

**Comment by JohnRachid** [comment]
Might be related: https://github.com/openvinotoolkit/openvino/issues/478

**Comment by messmor** [comment]
Running this on linux (ubuntu 20). The issue turned was python versioning related. After moving from python 3.7.1 to 3.8 the problem no longer persists. Everything is working now.
