### ISSUE TITLE
Does Nebullvm support detectron2?

### ISSUE THREAD

**Issue by mst019** [nebuly-ai/nebullvm#70]
Hi,

I'm working on a project that contains different models. One of those models is detectron2( which I'm not trying to optimize). However, when I install and import the nebullvm library on colab, the detectron2 librairies don't work anymore. Is there a way to fix that?

**Comment by valeriosofi** [comment]
Hi @mst019, could you please provide some more details on the error? I tried the official detectron2 Colab notebook (https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5), and after installing and importing nebullvm everything works for me.
