### ISSUE TITLE
meansure running time with median latency

### ISSUE THREAD

**Issue by reiase** [nebuly-ai/nebullvm#77]
Hi, I notice that nebullvm sometimes runs very slow on large models, and found that nebullvm currently uses mean latency to measure the running time of the optimized model in `compute_optimized_running_time(
    optimized_model: BaseInferenceLearner, steps: int = 100)`. Could it be better if using median latency? Also, we could use an adaptive algorithm to reduce total running steps?

**Comment by valeriosofi** [comment]
Hi @reiase, thanks for the contribution! Just a little question, why do you say that the median would be better compared to mean? Usually the advantage of the median is that it's less affected by outliers. Currently, the code calculates the running time by giving the model 100 tensors as input and calculating the mean. Have you found in your experiments that some of the times are much greater than others? Have you collected any data that you can share with us? Regarding the adaptive algorithm it's a great idea, as soon as we can we will review your PR.

**Comment by reiase** [comment]
Hi @valeriosofi, the main reason for suggesting the median is to speed up nebullvm on my MacBook.

I was coding on a MacBook with an M1 chip. Running model inference 100 times is painful because PyTorch does not support the accelerator on the M1 chip very well. When nebullvm searches for the best quantization strategy, it runs 100 times inference for every quantization type and backend. I have to wait for nearly an hour. 

The main idea of this issue is to estimate the running time of the optimized model with an adaptive algorithm that supports early stopping.  Early stopping is supported by both the moving mean and moving median, but the moving median is much more stable and converges faster when an outlier exists.

**Comment by valeriosofi** [comment]
Hi @reiase, I understand clearly the need for the adaptive algorithm to limit the number of iterations, about the median we are not so sure that it converges faster than the mean, because we have no evidence that there are many outliers. If in your experiments you found evidence that by using the median the algorithm performs less iterations I would ask you to share the experiment results with us so that we can evaluate them and we can accept the change.

**Comment by reiase** [comment]
Hi @valeriosofi, here are some of the experiment results when optimizing `resnext50_32x4d` from torch benchmark https://github.com/pytorch/benchmark:

1. Optimizing with PytorchBackendOptimizer and q_type: None 
raw:       0.0306 0.0310 0.0256 0.0239 0.0236 0.0238 0.0249
mean:    0.0306 0.0308 0.0291 0.0278 0.0269 0.0264
median: 0.0306 0.0308 0.0306 0.0281 0.0256 0.0247


2.  Optimizing with ONNXOptimizer and q_type: None
raw:       0.0376 0.0361 0.0127 0.0140 0.0143 0.0140 0.0169
mean:    0.0376 0.0368 0.0288 0.0251 0.0229 0.0214
median: 0.0376 0.0368 0.0361 0.0250 0.0143 0.0141

The leading values are outliers, the model seems to be slow because of warmup.

**Comment by valeriosofi** [comment]
Hi @reaise, thanks for sharing your benchmark! From your results I can see too that warmup could be an issue and that the median would be better, we will review your PR and accept the change! Thanks for the contribution!
