### ISSUE TITLE
optimize_model - Information about the best performing optim method

### ISSUE THREAD

**Issue by pyvandenbussche** [nebuly-ai/nebullvm#92]
Hi,

Thank you for this easy to use library. I'm using successfully using the `optimize_model()` function as per your notebook. 
I would like to know at the end, which optim method led to the `optimized_model`.
Is there any way to have this information from the returned `InferenceLearner` object?

Thank you!

**Comment by valeriosofi** [comment]
Hi @pyvandenbussche, we are happy to hear that you are using successfully the library! Knowing which optimization was used on your model is very easy, you have just to see the type of the inference learner that is returned by the optimize_model function! For example, If onnx was used, the inference learner would have a type similar to OnnxInferenceLearner.

**Comment by pyvandenbussche** [comment]
Thanks for your answer. So what does `HuggingFaceInferenceLearner` means in my case?
Does this mean that the original model (pytorch fp16) was performing better than using optimizations: ('onnxruntime', 'tensor RT', 'openvino')? Or may be this indicates that those optimization compilers did not run normally?

**Comment by valeriosofi** [comment]
Hi @pyvandenbussche, sorry for the late reply, hugging face models are always wrapped with the HuggingFaceInferenceLearner class. In this case, if you want details about which optimizer was used, you can see the type of `optimized_model.core_inference_learner`.

**Comment by pyvandenbussche** [comment]
Thank you.
